// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcLpw82WzA4Sa3qiZA7rpGm5ZIQkFZbQQ',
    appId: '1:114740457194:web:d28c8193adc499ecd1b193',
    messagingSenderId: '114740457194',
    projectId: 'ragify-dev-new',
    authDomain: 'ragify-dev-new.firebaseapp.com',
    storageBucket: 'ragify-dev-new.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdiKQ9azPzk-uRb580CeX5gzaoVTkOIDo',
    appId: '1:114740457194:android:750894a1a6db07d1d1b193',
    messagingSenderId: '114740457194',
    projectId: 'ragify-dev-new',
    storageBucket: 'ragify-dev-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2tlnpw-NFyEhhG8bOzxWatHAbA0c3GmA',
    appId: '1:114740457194:ios:987281757aa66d3cd1b193',
    messagingSenderId: '114740457194',
    projectId: 'ragify-dev-new',
    storageBucket: 'ragify-dev-new.firebasestorage.app',
    iosBundleId: 'com.enigmatek.pk.ragify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcLpw82WzA4Sa3qiZA7rpGm5ZIQkFZbQQ',
    appId: '1:114740457194:web:194f8e9b2febf0dad1b193',
    messagingSenderId: '114740457194',
    projectId: 'ragify-dev-new',
    authDomain: 'ragify-dev-new.firebaseapp.com',
    storageBucket: 'ragify-dev-new.firebasestorage.app',
  );
}
