// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHJeEdVvRXdIQDhLO3OFEnuoOENBJwKF8',
    appId: '1:177144805134:web:377e270f42797253b8495f',
    messagingSenderId: '177144805134',
    projectId: 'ragify-firebase-dev',
    authDomain: 'ragify-firebase-dev.firebaseapp.com',
    storageBucket: 'ragify-firebase-dev.firebasestorage.app',
    measurementId: 'G-KWZJED8R77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5d4p66dO4Ef_XYpa5uyPYSHPatIqLDaI',
    appId: '1:177144805134:android:1b2cfc3dc82a6652b8495f',
    messagingSenderId: '177144805134',
    projectId: 'ragify-firebase-dev',
    storageBucket: 'ragify-firebase-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0PWykk0-vOA8i-jgTftC87dpFcwKngY4',
    appId: '1:177144805134:ios:21d6af0a97153f16b8495f',
    messagingSenderId: '177144805134',
    projectId: 'ragify-firebase-dev',
    storageBucket: 'ragify-firebase-dev.firebasestorage.app',
    iosBundleId: 'com.enigmatek.pk.ragify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHJeEdVvRXdIQDhLO3OFEnuoOENBJwKF8',
    appId: '1:177144805134:web:c745e2d7124e36f3b8495f',
    messagingSenderId: '177144805134',
    projectId: 'ragify-firebase-dev',
    authDomain: 'ragify-firebase-dev.firebaseapp.com',
    storageBucket: 'ragify-firebase-dev.firebasestorage.app',
    measurementId: 'G-DEM2QZMT23',
  );
}
